### ISSUE TITLE
nHentai proxy stop working

### ISSUE THREAD

**Issue by sesgrinder** [appu1232/cubarimoe#10]
When attempt to access nHentai proxy page, cubari.moe return
"Could not complete the request due to the following error: External API error. 500 . Server Error"
AFAIK, this is introduced by nHentai implement DDoS protection on their pages and the usual page-scraping is no more. This is also mentioned in https://github.com/Dar9586/NClientV2/issues/402.

**Comment by funkyhippo** [comment]
Looks like they dialed back their anti-scraping measures so I'm closing this for now. Feel free to open it if you come across the issue again.

**Comment by BrutuZ** [comment]
It's back
