### ISSUE TITLE
Access of gists on private repos

### ISSUE THREAD

**Issue by BrutuZ** [appu1232/cubarimoe#11]
Would it be possible to add support for accessing gist\json files on private repositories on GitHub?

I thought of something like optionally adding the [Personal Access Token](https://github.com/settings/tokens) (with `repo` scope) ~~to the end of the URL~~ and passing it on requests if present.

~~Something like `https://cubari.moe/gist/raw/<usual_gist_path>/<optional_PAT>`. Would be a matter of checking whether the last URL segment was 40 characters long and started with `ghp_` to decide if the `Authorization: token <PAT>` header should be included in the HTTP request for the raw file.~~

Having the token on local\remote storage should be more convenient to the user and likely more secure as well since it can't be decoded from the URL

**Comment by funkyhippo** [comment]
Could you describe your use case?

Since the series content is parsed on the server, the token will have to be passed in some form which would make this insecure. As far as I'm aware, there isn't any way you could generate tokens limited to specific repositories (without going through the hoops of creating a new user, for example), so I'd like to know more about your use case before making a comment on it.

**Comment by BrutuZ** [comment]
Sure, I'm not comfortable exposing all the content I read, which is why I'm using Gists for the moment, but there's no way to organize or properly manage (git) them.
I tried creating another account only for that repo, but turns out having more than one free account is against GitHub policy and the account becomes flagged, which makes it basically exclusively private. I can commit to the repository and everything just fine, but only I can access it even though it is set as public.

For reference: https://github.com/unrelated-user/cubari-gists
![image](https://user-images.githubusercontent.com/7104931/159301405-b889bb61-29ad-4f8a-94b6-d778bb802f3a.png)

**Comment by funkyhippo** [comment]
That's certainly a niche use case, but I'm happy to facilitate it within reason.

Are you looking to completely distance your account(s) from the series metadata or are you simply trying to limit public visibility? If it's the latter, you could create an unlisted gist; the raw contents of unlisted gists can be accessed normally with a link, while not showing up in the public aggregates on your profile.

If it's the former, then I only really see two ways of approaching it, one of which you've already suggested. However, that would expose the token to the world and grant read/write access to _all_ your private repos. Another option would be for us to create a GitHub app that users can install on their repos, and all our subsequent requests will bear the credentials necessary to access the content.

I'm not a huge fan of that last one, but it would remove the need to pass tokens around.

**Comment by BrutuZ** [comment]
A bit of both in a sense. I don't mind keeping the json on this account if I'm the only one that can see it, hence my current use of gist.github.com.
~~But as I mentioned, gists are a hassle to manage, there's no organization (they're all just thrown in there sorted by last creation date, no subfolders or anything) and basically web-only. You can technically `git clone` them, but it's even messier since the "repo" name is the gist's hash...~~
As I typed this I realized I can add multiple files to a Secret GitHub Gist. That means I can just `git clone git@gist.github.com:X...X.git Gists-Folder` and have basically a publicly accessible but undisclosed json repository, which suits my needs well enough and doesn't require any dev work 😁
