### ISSUE TITLE
Support imgbb host

### ISSUE THREAD

**Issue by Ever4engel** [appu1232/cubarimoe#13]
Hey,

Is it possible to support this lossless image host as proxy please https://imgbb.com/ ?

here a sample link https://ibb.co/album/QXZ0mZ there is 20 images there.

anyway thanks a lot for your framework guys it serves a lot to many teams.

**Comment by funkyhippo** [comment]
Sure.

**Comment by funkyhippo** [comment]
Done.

Replace `imgbb.co` in the album URL with `cubari.moe`, eg. https://cubari.moe/album/QXZ0mZ
